name: Update configuration

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Init submodules
        run: git submodule update --init --recursive --remote
          
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install .

      - name: Clear out directory
        run: |
          set -e
          clearoutdir || exit 1
        continue-on-error: false

      - name: Run config setup
        run: |
          set -e
          setupconfigs || exit 1
        continue-on-error: false

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out/*
          git commit -m "CHORE: update configuration"
          git push

      - name: Create archive
        run: |
          cd out
          zip -r ../configurations.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: configurations
          path: configurations.zip
          if-no-files-found: error

  release:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: configurations
          path: configurations.zip

      - name: Generate release tag
        id: date
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          name: Release ${{ steps.date.outputs.tag }}
          files: configurations.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}