name: Update configuration

on:
  push:
    branches: [main, dev]
    paths:
      - '.github/workflows/update.yaml'
      - 'src/pz_modding_config/**'
      - 'out/**'
  pull_request:
    branches: [main, dev]
    paths:
      - '.github/workflows/update.yaml'
      - 'src/pz_modding_config/**'
      - 'out/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      changes_made: ${{ steps.commit.outputs.changes_made }}
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Init submodules
        run: git submodule update --init --recursive --remote
          
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install .

      - name: Clear out directory
        run: |
          set -e
          clearoutdir || exit 1
        continue-on-error: false

      - name: Run config setup
        run: |
          set -e
          setupconfigs || exit 1
        continue-on-error: false

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out/*
          if git diff --quiet && git diff --staged --quiet; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            git commit -m "CHORE: update configuration"
            git push
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

  release:
    needs: update
    if: needs.update.outputs.changes_made == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          ref: main

      - name: Generate release tag
        id: date
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          name: Release ${{ steps.date.outputs.tag }}
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}